<a href="https://colab.research.google.com/github/FayezAltawafshih/Data-Analyst-with-Python/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python** **Tutorial** **for** **Beginners**

**2.8**. **Functions** **in** **Python**

Functions

Function is a block of code that can be reused in a program

Factorial of a number

Factorial of a number is the product of all positive integers less than or equal to the given number

Factorial of 5 = 5 * 4 * 3 * 2 * 1 = 120

In [ ]:
number = int(input("Enter a number to find its factorial: "))

factorial = 1

if number == 0:
  print('The factorial of 0 is 1')

else:
  for i in range(1, number + 1):
    factorial = factorial * i
    print('The factorial of',number,'is',factorial)

Enter a number to find its factorial: 10
The factorial of 10 is 1
The factorial of 10 is 2
The factorial of 10 is 6
The factorial of 10 is 24
The factorial of 10 is 120
The factorial of 10 is 720
The factorial of 10 is 5040
The factorial of 10 is 40320
The factorial of 10 is 362880
The factorial of 10 is 3628800


In [ ]:
def factorial_value(num):
  factorial = 1
  if num == 0:
    return factorial
  else:
    for i in range(1, num + 1):
      factorial = factorial * i
    return factorial



In [ ]:
print(factorial_value(5))

120


Complete Numpy Tutorial in Python

Numpy - Numerical Python

Advantages of Numpy Arrays
1. Allows Several Mathmatical Operations
2. Faster Operations


In [ ]:
import numpy as np

In [ ]:
from time import process_time

Time Taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010065340000000589


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)
#

0.0015466180000007768


Numpy Arryas

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a one dimantional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
# Creating b one Dinantional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)

print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array withe random values
b  = np.random.random((3,4))
print(b)

[[0.90008217 0.49278358 0.98925386 0.43731159]
 [0.68978797 0.41936137 0.99120487 0.20061472]
 [0.75248926 0.28473724 0.81923329 0.11361416]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[26 16 85 87 45]
 [48 50 40 32 95]
 [94 82 92 75 41]]


In [ ]:
# array of evenly spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[79 17 78 48 84]
 [28 24 82 71 17]
 [73 54 44 45 64]
 [20 67 85 52 48]
 [51 24 80 51 78]]


In [ ]:
# array dimesion
print(c.shape)

(5, 5)


In [ ]:
# number of dimesions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on a np.array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))



In [ ]:
print(a)
print(b)

[[0 0 1]
 [1 1 4]
 [6 4 0]]
[[11 13 10]
 [16 11 14]
 [18 16 13]]


In [ ]:
print(a.ndim)
print(b.ndim)

2
2


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[11 13 11]
 [17 12 18]
 [24 20 13]]
[[-11 -13  -9]
 [-15 -10 -10]
 [-12 -12 -13]]
[[  0   0  10]
 [ 16  11  56]
 [108  64   0]]
[[0.         0.         0.1       ]
 [0.0625     0.09090909 0.28571429]
 [0.33333333 0.25       0.        ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[0 6 1]
 [9 8 3]
 [2 8 4]]
[[19 18 18]
 [18 18 12]
 [15 19 19]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 24 19]
 [27 26 15]
 [17 27 23]]
[[-19 -12 -17]
 [ -9 -10  -9]
 [-13 -11 -15]]
[[  0 108  18]
 [162 144  36]
 [ 30 152  76]]
[[0.         0.33333333 0.05555556]
 [0.5        0.44444444 0.25      ]
 [0.13333333 0.42105263 0.21052632]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 1 0]
 [4 8 1]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 4]
 [1 8]
 [0 1]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 4]
 [1 8]
 [0 1]]
(3, 2)


In [ ]:
# resheabing a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 6 2]
 [9 6 9]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 6]
 [2 9]
 [6 9]]
(3, 2)
